k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: true
  crumbsless: false
  readOnly: true
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: arn:aws:eks:ap-southeast-2:349416450876:cluster/geo-dev
  currentCluster: arn:aws:eks:ap-southeast-2:349416450876:cluster/geo-dev
  clusters:
    arn:aws:eks:ap-southeast-2:349416450876:cluster/geo-dev:
      namespace:
        active: argocd
        favorites:
        - argocd
        - all
        - default
      view:
        active: deployments
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    minikube:
      namespace:
        active: argocd
        favorites:
        - argocd
        - kube-system
        - traefik
        - underground
        - sealed-secrets
        - monitoring
        - ltp
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
