#!/usr/bin/env sh

#sudo pacman --needed --noconfirm -S\
#  awesome\
#  awesome-freedesktop\
#  base-devel\
#  exa\
#  git\
#  imagemagick\
#  jq\
#  kitty\
#  nvm\
#  redshift\
#  ripgrep\
#  rofi\
#  xclip\
#  xdotool\
#  yarn\
#  yay

#yay --needed --noconfirm -S\
#  google-chrome\
#  neovim-git\
#  zsa-wally

#mkdir ~/repos
#git clone https://github.com/Jumbub/dotfiles.git ~/repos/dotfiles
#~/repos/dotfiles/scripts/1-copydotfiles

# Install awesome WM dependencies
rm ~/.config/awesome/awesome-wm-widgets
git clone https://github.com/streetturtle/awesome-wm-widgets.git ~/.config/awesome/awesome-wm-widgets

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc
