#!/usr/bin/env sh

# Install packages
sudo pacman --needed --noconfirm -S\
  base-devel\
  ccls\
  cmake\
  corepack\
  entr\
  eza\
  fd\
  fzf\
  git\
  i3lock\
  imagemagick\
  jq\
  kitty\
  man-db\
  man-pages\
  neovim\
  noto-fonts-cjk\
  noto-fonts-emoji\
  noto-fonts-emoji\
  noto-fonts-extra\
  noto-fonts\
  npm\
  picom\
  pnpm\
  prettier\
  redshift\
  ripgrep\
  rofi\
  scrot\
  stylua\
  typescript\
  unzip\
  xclip\
  xdotool\
  yay\
  zsh

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
