#!/usr/bin/env sh

# Install packages
sudo pacman --needed --noconfirm -S\
  base-devel\
  exa\
  fd\
  fzf\
  git\
  imagemagick\
  jq\
  kitty\
  man\
  neovim\
  noto-fonts-emoji\
  npm\
  pnpm\
  picom\
  prettier\
  redshift\
  ripgrep\
  rofi\
  stylua\
  typescript\
  xclip\
  xdotool\
  zsh

yay --needed --noconfirm -S\
  awesome-freedesktop-git\
  rofi-greenclip\
  google-chrome\
  zsa-wally

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
