#!/usr/bin/env sh

# pacman
sudo pacman --needed --noconfirm -S\
  awesome\
  base-devel\
  ccls\
  cmake\
  corepack\
  entr\
  eza\
  fd\
  fzf\
  git\
  i3lock\
  imagemagick\
  jq\
  kitty\
  man-db\
  man-pages\
  ncdu\
  neovim\
  noto-fonts-cjk\
  noto-fonts-emoji\
  noto-fonts-emoji\
  noto-fonts-extra\
  noto-fonts\
  picom\
  prettier\
  redshift\
  ripgrep\
  rofi\
  scrot\
  stylua\
  unzip\
  xclip\
  xdotool\
  zsh

# yay
yay --needed --noconfirm -S\
  awesome-freedesktop-git\
  rofi-greenclip\
  zsa-wally

# oh-my-zsh
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.custom-oh-my-zsh/themes/powerlevel10k
git clone --depth=1 https://github.com/unixorn/fzf-zsh-plugin.git $HOME/.custom-oh-my-zsh/plugins/fzf-zsh-plugin
git clone https://github.com/zsh-users/zsh-completions $HOME/.custom-oh-my-zsh/plugins/zsh-completions
