#!/usr/bin/env bash

set -e

# Warn user about potential changes
cp $HOME/repos/dotfiles/.gitignore $HOME/.gitignore
git --work-tree=$HOME --git-dir=$HOME/repos/dotfiles/.git status
if ! $HOME/repos/dotfiles/scripts/confirm
then
	echo "Aborting"
	exit
fi

# Copy over dotfiles
git --work-tree=$HOME --git-dir=$HOME/repos/dotfiles/.git checkout -- $HOME
cp -R $HOME/repos/dotfiles/.git $HOME/repos/dotfiles.git

# Change to ssh remote for dotfiles
git --work-tree=$HOME --git-dir=$HOME/repos/dotfiles.git remote set-url origin git@github.com:Jumbub/dotfiles.git

# Copy default git config template
cp $HOME/scripts/storage/.gitconfig $HOME/.gitconfig

# Machine specific config
touch ~/.config/kitty/machine.conf
