#!/usr/bin/env sh

set -e

# Install dotfiles
mkdir -p ~/repos
rm -rf ~/repos/dotfiles
git clone --recurse-submodules https://github.com/Jumbub/dotfiles.git ~/repos/dotfiles

# Warn user about potential changes
cp $HOME/repos/dotfiles/.gitignore $HOME/.gitignore
git --work-tree=$HOME --git-dir=$HOME/repos/dotfiles/.git status
if ! $HOME/repos/dotfiles/scripts/confirm
then
	echo "Aborting"
	exit
fi

# Copy over dotfiles
git --work-tree=$HOME --git-dir=$HOME/repos/dotfiles/.git checkout -- $HOME
cp -R $HOME/repos/dotfiles/.git $HOME/repos/dotfiles.git

# Copy default git config template
cp $HOME/scripts/storage/.gitconfig $HOME/.gitconfig

# Change to ssh remote for dotfiles
dot remote set-url origin git@github.com:Jumbub/dotfiles.git

# Install plugins
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
git clone https://github.com/agkozak/zsh-z ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-z
git clone https://github.com/lukechilds/zsh-nvm ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-nvm
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Setup yarn
yarn config set prefix ~/.yarn
yarn global add prettier\
  typescript\
  intelephense\

