#!/usr/bin/env sh

set -e

# Install dotfiles
mkdir -p ~/repos
rm -rf ~/repos/dotfiles
git clone --recurse-submodules https://github.com/Jumbub/dotfiles.git ~/repos/dotfiles

# Warn user about potential changes
cp $HOME/repos/dotfiles/.gitignore $HOME/.gitignore
git --work-tree=$HOME --git-dir=$HOME/repos/dotfiles/.git status
if ! $HOME/repos/dotfiles/scripts/confirm
then
	echo "Aborting"
	exit
fi

# Copy over dotfiles
git --work-tree=$HOME --git-dir=$HOME/repos/dotfiles/.git checkout -- $HOME
cp -R $HOME/repos/dotfiles/.git $HOME/repos/dotfiles.git

# Copy default git config template
cp $HOME/scripts/storage/.gitconfig $HOME/.gitconfig

source $HOME/.zshrc

# Change to ssh remote for dotfiles
dot remote set-url origin git@github.com:Jumbub/dotfiles.git
