#!/usr/bin/env sh

set -e

# Install plugins
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM}/plugins/zsh-completions
git clone https://github.com/agkozak/zsh-z ${ZSH_CUSTOM}/plugins/zsh-z
git clone https://github.com/lukechilds/zsh-nvm ${ZSH_CUSTOM}/plugins/zsh-nvm
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM}/themes/powerlevel10k

# Setup yarn
yarn config set prefix ~/.yarn
yarn global add prettier\
  typescript\
  intelephense\

