#!/bin/bash

if [ $1 ] && [ $2 ]
then

  cd ..
  cp -R $1 $2
  cd $2
  for file in * ; do mv $file ${file//$1/$2} ; done
  sed -i "s/$1/$2/g" "$2.tsx"
  sed -i "s/$1/$2/g" "$2.stories.tsx"

else

  echo 'clonecomponent <old> <new>'

fi
