#!/bin/python3

import argparse
import os
import distutils
from distutils import dir_util

parser = argparse.ArgumentParser()
parser.add_argument('newName')

args = parser.parse_args()

newName = args.newName

print(f'Creating a new component named {newName}')

oldName = os.getcwd().split('/')[-1]

print(f'From the current component named {oldName}')

oldLocation = '../%s' % oldName
newLocation = '../%s' % newName

dir_util.copy_tree(oldLocation, newLocation)

print(f'Cloned folder from {oldLocation} to {newLocation}')

for file in os.listdir(oldLocation):
  oldFile = open(f'{file}', "rt")
  newFile = open(f'{newLocation}/{file.replace(oldName, newName)}', "wt")

  for line in oldFile:
    newFile.write(line.replace(oldName, newName))

  oldFile.close()
  newFile.close()

print(f'Replaced word {oldName} with {newName} in {newLocation}')


