#!/bin/sh

# Colours derived from: https://github.com/gerardroche/sublime-monokai-free
# Shades derived from: https://www.color-hex.com/color/f92672

export THEME_BLACK="#272822"
export THEME_WHITE="#dfdfd9"

export THEME_GRAY_DARKER="#3A382F"
export THEME_GRAY_DARK="#5D5A4B"
export THEME_GRAY="#75715e"
export THEME_GRAY_LIGHT="#908D7E"
export THEME_GRAY_LIGHTER="#BAB8AE"

export THEME_YELLOW_DARK="#b8af5c"
export THEME_YELLOW="#e6db74"
export THEME_YELLOW_LIGHT="#EBE28F"

export THEME_RED_DARK="#c71e5b"
export THEME_RED="#f92672"
export THEME_RED_LIGHT="#fa518e"

export THEME_ORANGE_DARK="#CA7818"
export THEME_ORANGE="#fd971f"
export THEME_ORANGE_LIGHT="#fdab4b"

export THEME_GREEN_DARK="#84b424"
export THEME_GREEN="#a6e22e"
export THEME_GREEN_LIGHT="#b7e757"

export THEME_BLUE_DARK="#51adbf"
export THEME_BLUE="#66d9ef"
export THEME_BLUE_LIGHT="#84e0f2"

export THEME_CYAN_DARK="#80BFB6"
export THEME_CYAN="#a1efe4"
export THEME_CYAN_LIGHT="#b3f2e9"

export THEME_PINK_DARK="#ca4cc0"
export THEME_PINK="#fd5ff0"
export THEME_PINK_LIGHT="#fd7ef3"

export THEME_PURPLE_DARK="#8b67cc"
export THEME_PURPLE="#ae81ff"
export THEME_PURPLE_LIGHT="#be9aff"

if [[ -n $1 ]]
then
  echo ${!1}
fi
