#!/usr/bin/zsh

function devcontainerExec {
  devcontainer exec \
    --workspace-folder . \
    --remote-env THIS_ENVIRONMENT_LABEL="$(basename `pwd`)" \
    -- $@
}

function devcontainerUp {
  devcontainer up \
    --workspace-folder . \
    --expect-existing-container
}

function devcontainerUpNew {
  source ~/secrets/devcontainer.sh

  devcontainer up \
    --workspace-folder . \
    --remove-existing-container
}

function devcontainerExecNew {
  source ~/secrets/devcontainer.sh

  devcontainerExec bash -s << EOF
    mkdir -p ~/.local/bin
    mkdir -p ~/.config
    cd ~

    git config --global user.email "james@example.com"
    git config --global user.name "james-bray"
    git config --global core.editor "nvim"
    git config --global pull.ff "only"
    git config --global url."https://james-bray:$EVT_GITHUB_TOKEN@github.eagleview.com".insteadOf "https://github.eagleview.com"

    sudo apt update &&
      sudo apt install -y zsh gcc unzip wget tar &&
      sudo chsh -s /usr/bin/zsh

    yes n | sh -c "\$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" &&
      git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \$HOME/.custom-oh-my-zsh/themes/powerlevel10k &&
      git clone --depth=1 https://github.com/unixorn/fzf-zsh-plugin.git \$HOME/.custom-oh-my-zsh/plugins/fzf-zsh-plugin &&
      git clone --depth=1 https://github.com/zsh-users/zsh-completions \$HOME/.custom-oh-my-zsh/plugins/zsh-completions

    ARCH=x86_64
    AARCH=amd64

    PACKAGE=nvim-linux-\$ARCH
    wget -q https://github.com/neovim/neovim/releases/download/v0.11.4/\$PACKAGE.tar.gz &&
      tar -xf \$PACKAGE.tar.gz &&
      cp -R \$PACKAGE/* ~/.local &&
      rm -rf \$PACKAGE \$PACKAGE.tar.gz

    PACKAGE=eza_\$ARCH-unknown-linux-gnu
    wget -q https://github.com/eza-community/eza/releases/download/v0.23.4/\$PACKAGE.tar.gz &&
      tar -xf \$PACKAGE.tar.gz &&
      mv eza ~/.local/bin/ &&
      rm \$PACKAGE.tar.gz

    PACKAGE=fzf-0.66.1-linux_\$AARCH
    wget -q https://github.com/junegunn/fzf/releases/download/v0.66.1/\$PACKAGE.tar.gz &&
      tar -xf \$PACKAGE.tar.gz &&
      mv fzf ~/.local/bin/ &&
      rm \$PACKAGE.tar.gz

    # roslyn requires at least version 9
    dotnet --version &&
      ! dotnet --list-runtimes | grep 9.0 &&
      wget https://dot.net/v1/dotnet-install.sh &&
      chmod +x dotnet-install.sh &&
      ./dotnet-install.sh --channel 9.0 --runtime dotnet &&
      sudo mv ~/.dotnet/shared/Microsoft.NETCore.App/9.0.* /usr/share/dotnet/shared/Microsoft.NETCore.App &&
        wget https://github.com/Crashdummyy/roslynLanguageServer/releases/download/5.3.0-1.25524.13/microsoft.codeanalysis.languageserver.linux-x64.zip &&
        unzip microsoft.codeanalysis.languageserver.linux-x64.zip -d \$HOME/.local/bin/

    go version &&
      go install golang.org/x/tools/gopls@latest &&
      go install github.com/go-delve/delve/cmd/dlv@latest

    git clone --depth=1 https://github.com/Jumbub/dotfiles.git \$HOME/dotfiles &&
      git --work-tree=\$HOME --git-dir=\$HOME/dotfiles/.git checkout -- \$HOME

    \$HOME/.local/bin/nvim --headless -c 'quit'
EOF
}

function dc {
  if [ "$#" -ne "0" ]; then
    devcontainerExec $@
  else
    devcontainerExec zsh
  fi
}

function dcu {
  devcontainerUp || (devcontainerUpNew && devcontainerExecNew)
}