#!/usr/bin/env bash

LOG_FILE=/tmp/install_programs.txt
log() {
  echo "$@" >> $LOG_FILE
}

echo "" > $LOG_FILE
log "beginning install..."

install_program() {
  log "installing ${2}..."
  $@
  if [[ $? > 0 ]]
  then
    log "ERROR: failed to install $2 ($1 $2)"
  else
    log "installed ${2}"
  fi
}

if [ ! $1 ] || [ "$1" = "firsttime" ] || [ "$1" = "aptRepos" ]
then
  # Sublime
  wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
  sudo apt install apt-transport-https
  echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

  # PHP
  sudo add-apt-repository -y ppa:ondrej/php

  #  Node
  curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

  # NeoVim
  sudo add-apt-repository -y ppa:neovim-ppa/stable

  # Prolog
  sudo add-apt-repository -y ppa:swi-prolog/stable
fi

if [ ! $1 ] || [ "$1" = "apt" ]
then
  sudo apt update
  install_apt() {
    install_program "sudo apt install -y" "${@}"
  }
  install_apt apt-transport-https
  install_apt autokey-gtk
  install_apt awesome
  install_apt ca-certificates
  install_apt clang
  install_apt ctags
  install_apt curl
  install_apt dconf-editor
  install_apt default-jdk
  install_apt fonts-firacode
  install_apt gnupg2
  install_apt haskell-stack
  install_apt htop
  install_apt libxft-dev
  install_apt lolcat
  install_apt lua5.3
  install_apt liblua5.3-dev
  install_apt luarocks
  install_apt ninja-build
  install_apt nodejs
  install_apt neovim
  install_apt php
  install_apt php-curl
  install_apt php-mbstring
  install_apt php-xml
  install_apt php7.2
  install_apt php7.2-curl
  install_apt php7.2-mbstring
  install_apt php7.2-soap
  install_apt php7.2-xml
  install_apt php7.2-zip
  install_apt python3
  install_apt python3-pip
  install_apt redshift
  install_apt redshift-gtk
  install_apt rofi
  install_apt silversearcher-ag
  install_apt software-properties-common
  install_apt sublime-merge
  install_apt sublime-text
  install_apt swi-prolog
  install_apt vim
  install_apt vlc
  install_apt xournal
  install_apt zsh

  # https://github.com/elw00d/awesome-deb-docker
fi

# Docker (https://docs.docker.com/install/linux/docker-ce/ubuntu/)
if [ ! $1 ] || [ "$1" = "firsttime" ]
then
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

  sudo apt-get update

  sudo apt-get install -y docker-ce docker-ce-cli containerd.io
fi

if [ ! $1 ] || [ "$1" = "snap" ]
then
  install_snap() {
    install_program "sudo snap install" "${@}"
  }
  install_snap spotify
  install_snap code --classic
  install_snap gotop-cjbassi
fi

if [ "$1" = "codeupdate" ]
then
  code --list-extensions > $HOME/scripts/.code_extensions
fi

if [ ! $1 ] || [ "$1" = "code" ]
then
  install_code() {
    install_program "code --install-extension" "${@}"
  }
  cat $HOME/scripts/.code_extensions | xargs -L 1 code --install-extension
fi

if [ "$1" = "codelualang" ]
then
  REPO_PATH=$HOME/repos/lua-language-server

  git clone https://github.com/sumneko/lua-language-server $REPO_PATH
  cd $REPO_PATH
  git submodule update --init --recursive

  cd 3rd/luamake
  ninja -f ninja/linux.ninja
  cd -

  $REPO_PATH/3rd/luamake/luamake rebuild

  $REPO_PATH/build/lua make/copy.lua $HOME/.vscode/extensions/sumneko.lua*
fi

if [ ! $1 ] || [ "$1" = "pip" ]
then
  install_pip() {
    install_program "pip3 install" "${@}"
  }
  install_pip awscli
fi

if [ ! $1 ] || [ "$1" = "firsttime" ]
then
  # Is this broken? Go to https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
  install_npm() {
    install_program "npm i -g" "${@}"
  }
  install_npm npm
  install_npm yarn
fi

if [ ! $1 ] || [ "$1" = "yarn" ]
then
  install_yarn() {
    install_program "yarn global add" "${@}"
  }
  install_yarn prettier
  install_yarn @prettier/plugin-lua
  install_yarn typescript
  install_yarn intelephense
fi


if [ ! $1 ] || [ "$1" = "luarocks" ]
then
  install_luarocks() {
    install_program "luarocks install --local" "${@}"
  }
  install_luarocks "--server=http://luarocks.org/dev lua-lsp"
  install_luarocks "luacheck"
  install_luarocks "lcf"
fi

if [ ! $1 ] || [ "$1" = "kitty" ]
then
  curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  ln -s ~/.local/kitty.app/bin/kitty ~/.local/bin/
fi

if [ ! $1 ] || [ "$1" = "fzf" ]
then
  FZF_DIR=$HOME/.fzf
  if ! [[ -d $FZF_DIR ]]
  then
    git clone --depth 1 https://github.com/junegunn/fzf.git $FZF_DIR
  fi
  $FZF_DIR/install --all
fi

log "done.\n"
cat $LOG_FILE
