#!/usr/bin/env zsh

if [[ -x nvm ]]
then

  # Create a list of apps that require nvm
  REQUIRE_NVM_SOURCE=(`find ~/.nvm/versions/node -maxdepth 3 -type l -wholename '*/bin/*' | xargs -n1 basename | sort | uniq`)
  REQUIRE_NVM_SOURCE+=("node")
  REQUIRE_NVM_SOURCE+=("nvm")
  REQUIRE_NVM_SOURCE+=("yarn")

  # Lazy source nvm when using nvm apps
  load_nvm () {
    echo "🚨 NVM not loaded! Loading now..."
    source /usr/share/nvm/init-nvm.sh
  }

  # Making node global trigger the lazy loading
  for cmd in "${REQUIRE_NVM_SOURCE[@]}"; do
    eval "${cmd}(){ unset -f ${REQUIRE_NVM_SOURCE}; load_nvm; ${cmd} \$@ }"
  done

fi
