#!/usr/bin/env sh

(haveigot scrot && haveigot convert &&
  scrot "/tmp/screenshot.png" &&
  convert "/tmp/screenshot.png" -blur 0x12 "/tmp/blurred-screenshot.png" &&
  i3lock -i "/tmp/blurred-screenshot.png") || i3lock
