#!/usr/bin/env zsh

source $HOME/.aliases

local runner="$1"
local processName="$2"
local notify=false
local complain=false

# Notify if requested
if [ "--notify" = "$1" ]
then
  runner="$2"
  processName="$3"
  notify=true
fi

# Ensure correct usage
if [[ -z "$runner" ]]
then
  if [ "true" = "$notify" ]
  then
    notify-send "Usage: run-if-not [--notify] command [processName]" &
  fi
  echo "Usage: run-if-not [--notify] command [processName]"
  exit 1
fi

# Use runner as processName if none provided
if [[ -z "$processName" ]]
then
  processName="$runner"
fi

# Check command exists
runnerCommand="`echo "$runner" | head -n1 | awk '{print $1;}'`"
echo "$runnerCommand"
if haveigot "$runnerCommand"
then
  # Check command isn't already running
  if ! pgrep "$processName"
  then
    echo $runner | zsh &
    if [ "true" = "$notify" ]
    then
      # notify-send "Started: $runner" &
    fi
  fi
else
  # Error when command does not exist
  if [ "true" = "$notify" ]
  then
    notify-send "Error: missing command '$runner'"
  fi
  echo "Error: missing command '$runner'"
  exit 1
fi
