#!/usr/bin/env zsh

source $HOME/.aliases

# Allow time for Rofi to fade
sleep 0.1

TIMESTAMP="`date +%s`"
PICTURE="$HOME/Pictures/screenshots/${TIMESTAMP}.png"
import -silent $PICTURE && xclip -selection clipboard -t image/png -i $PICTURE
img $PICTURE
