#!/usr/bin/env zsh

source $HOME/.aliases

# Allow time for Rofi to fade
sleep 0.1

TIMESTAMP="`date +%s`"
import -silent "$HOME/Pictures/screenshot${TIMESTAMP}.png" && xclip -selection clipboard -t image/png -i "$HOME/Pictures/screenshot${TIMESTAMP}.png"
img $HOME/Pictures/screenshot${TIMESTAMP}.png
