local awful = require("awful")
require("awful.autofocus")

local f = require("functions")
f.setupTheme()
f.setGlobals()
f.setupErrorHandlers()
f.setupLayouts()
f.setupScreens(screen)
f.setupClientRules()
f.setupClientSignals(client)
f.setupGlobalBindings()
f.asyncJobs()
